//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public GioHang()
        {
            this.GioHangChiTiets = new HashSet<GioHangChiTiet>();
        }
    
        public int MaGH { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual ICollection<GioHangChiTiet> GioHangChiTiets { get; set; }
    }
}
