//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class QL_BanGaRanEntities : DbContext
    {
        public QL_BanGaRanEntities()
            : base("name=QL_BanGaRanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public DbSet<GioHang> GioHangs { get; set; }
        public DbSet<GioHangChiTiet> GioHangChiTiets { get; set; }
        public DbSet<HoaDon> HoaDons { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<SanPham> SanPhams { get; set; }
        public DbSet<TaiKhoan> TaiKhoans { get; set; }
        public DbSet<ThanhToan> ThanhToans { get; set; }
    
        public virtual int sp_SuaSanPham(Nullable<int> maSP, string tenSP, Nullable<decimal> gia, string moTa, Nullable<int> soLuong, string anh, Nullable<int> maLoai)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(decimal));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var anhParameter = anh != null ?
                new ObjectParameter("Anh", anh) :
                new ObjectParameter("Anh", typeof(string));
    
            var maLoaiParameter = maLoai.HasValue ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaSanPham", maSPParameter, tenSPParameter, giaParameter, moTaParameter, soLuongParameter, anhParameter, maLoaiParameter);
        }
    
        public virtual int sp_TaoHoaDon(Nullable<int> maKH, Nullable<int> maNV)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoHoaDon", maKHParameter, maNVParameter);
        }
    
        public virtual int sp_ThemChiTietHoaDon(Nullable<int> maHD, Nullable<int> maSP, Nullable<int> soLuong, Nullable<decimal> donGia)
        {
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChiTietHoaDon", maHDParameter, maSPParameter, soLuongParameter, donGiaParameter);
        }
    
        public virtual int sp_ThemSanPham(string tenSP, Nullable<decimal> gia, string moTa, Nullable<int> soLuong, string anh, Nullable<int> maLoai)
        {
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(decimal));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var anhParameter = anh != null ?
                new ObjectParameter("Anh", anh) :
                new ObjectParameter("Anh", typeof(string));
    
            var maLoaiParameter = maLoai.HasValue ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemSanPham", tenSPParameter, giaParameter, moTaParameter, soLuongParameter, anhParameter, maLoaiParameter);
        }
    
        public virtual int sp_XoaSanPham(Nullable<int> maSP)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaSanPham", maSPParameter);
        }
    }
}
