//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhToan
    {
        public int MaTT { get; set; }
        public Nullable<int> MaHD { get; set; }
        public string PhuongThuc { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
    }
}
